name: Other metamodels

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        smalltalk-config: [ .github/workflows/famix-config.ston, .github/workflows/famixCpp-config.ston, .github/workflows/criticBrowser-config.ston, .github/workflows/famixFortran-config.ston ]
        smalltalk-image: [ Pharo64-10 , Pharo64-11 ]
        include:
          - smalltalk-config: .github/workflows/famix-config.ston
            name: Famix tests
          - smalltalk-config: .github/workflows/famixCpp-config.ston
            name: FamixCpp tests
          - smalltalk-config: .github/workflows/criticBrowser-config.ston
            name: CriticBrowser tests
          - smalltalk-config: .github/workflows/famixFortran-config.ston
            name: Fortran tests
        
    name: ${{ matrix.name }} - ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v3
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-image: ${{ matrix.smalltalk-image }}
      - run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-image }} ${{ matrix.smalltalk-config }}
        shell: bash
        timeout-minutes: 15
